/** Independently reviewed source membership. Do not derive this list from the
 * emitter: a changed source clause must produce a reviewed diff here. */
export const EXPECTED_HIGHER_SLOT_SPELL_KEYS = [
  'spell:acid-arrow',
  'spell:aid',
  'spell:animal-friendship',
  'spell:animal-messenger',
  'spell:animate-dead',
  'spell:animate-objects',
  'spell:arcane-hand',
  'spell:bane',
  'spell:banishment',
  'spell:bestow-curse',
  'spell:bless',
  'spell:blight',
  'spell:blindness-deafness',
  'spell:branding-smite',
  'spell:burning-hands',
  'spell:call-lightning',
  'spell:chain-lightning',
  'spell:charm-person',
  'spell:circle-of-death',
  'spell:cloudkill',
  'spell:color-spray',
  'spell:command',
  'spell:cone-of-cold',
  'spell:confusion',
  'spell:conjure-animals',
  'spell:conjure-celestial',
  'spell:conjure-elemental',
  'spell:conjure-fey',
  'spell:conjure-minor-elementals',
  'spell:conjure-woodland-beings',
  'spell:counterspell',
  'spell:create-or-destroy-water',
  'spell:create-undead',
  'spell:creation',
  'spell:cure-wounds',
  'spell:delayed-blast-fireball',
  'spell:disintegrate',
  'spell:dispel-magic',
  'spell:dominate-beast',
  'spell:dominate-monster',
  'spell:dominate-person',
  'spell:enhance-ability',
  'spell:etherealness',
  'spell:false-life',
  'spell:fireball',
  'spell:flame-blade',
  'spell:flame-strike',
  'spell:flaming-sphere',
  'spell:fly',
  'spell:fog-cloud',
  'spell:freezing-sphere',
  'spell:geas',
  'spell:globe-of-invulnerability',
  'spell:glyph-of-warding',
  'spell:guiding-bolt',
  'spell:heal',
  'spell:healing-word',
  'spell:heat-metal',
  'spell:hellish-rebuke',
  'spell:heroism',
  'spell:hold-monster',
  'spell:hold-person',
  'spell:hunters-mark',
  'spell:ice-storm',
  'spell:inflict-wounds',
  'spell:insect-plague',
  'spell:invisibility',
  'spell:lightning-bolt',
  'spell:longstrider',
  'spell:magic-circle',
  'spell:magic-missile',
  'spell:magic-weapon',
  'spell:major-image',
  'spell:mass-cure-wounds',
  'spell:mass-healing-word',
  'spell:mass-suggestion',
  'spell:modify-memory',
  'spell:moonbeam',
  'spell:phantasmal-killer',
  'spell:planar-binding',
  'spell:prayer-of-healing',
  'spell:private-sanctum',
  'spell:scorching-ray',
  'spell:shatter',
  'spell:sleep',
  'spell:spirit-guardians',
  'spell:spiritual-weapon',
  'spell:thunderwave',
  'spell:vampiric-touch',
  'spell:wall-of-fire',
  'spell:wall-of-ice',
  'spell:wall-of-thorns',
] as const;

export const EXPECTED_CHARACTER_LEVEL_SPELL_KEYS = [
  'spell:acid-splash',
  'spell:chill-touch',
  'spell:eldritch-blast',
  'spell:fire-bolt',
  'spell:poison-spray',
  'spell:produce-flame',
  'spell:ray-of-frost',
  'spell:sacred-flame',
  'spell:shocking-grasp',
  'spell:vicious-mockery',
] as const;

export const EXPECTED_HIGHER_SLOT_SOURCE_PAGES: Readonly<
  Record<string, number>
> = {
  'spell:acid-arrow': 114,
  'spell:aid': 114,
  'spell:animal-friendship': 115,
  'spell:animal-messenger': 115,
  'spell:animate-dead': 115,
  'spell:animate-objects': 116,
  'spell:arcane-hand': 118,
  'spell:bane': 120,
  'spell:banishment': 120,
  'spell:bestow-curse': 121,
  'spell:bless': 122,
  'spell:blight': 122,
  'spell:blindness-deafness': 122,
  'spell:branding-smite': 123,
  'spell:burning-hands': 123,
  'spell:call-lightning': 123,
  'spell:chain-lightning': 124,
  'spell:charm-person': 124,
  'spell:circle-of-death': 124,
  'spell:cloudkill': 125,
  'spell:color-spray': 125,
  'spell:command': 125,
  'spell:cone-of-cold': 127,
  'spell:confusion': 127,
  'spell:conjure-animals': 127,
  'spell:conjure-celestial': 127,
  'spell:conjure-elemental': 128,
  'spell:conjure-fey': 128,
  'spell:conjure-minor-elementals': 128,
  'spell:conjure-woodland-beings': 129,
  'spell:counterspell': 131,
  'spell:create-or-destroy-water': 132,
  'spell:create-undead': 132,
  'spell:creation': 132,
  'spell:cure-wounds': 132,
  'spell:delayed-blast-fireball': 133,
  'spell:disintegrate': 135,
  'spell:dispel-magic': 136,
  'spell:dominate-beast': 137,
  'spell:dominate-monster': 137,
  'spell:dominate-person': 138,
  'spell:enhance-ability': 139,
  'spell:etherealness': 140,
  'spell:false-life': 142,
  'spell:fireball': 144,
  'spell:flame-blade': 145,
  'spell:flame-strike': 145,
  'spell:flaming-sphere': 145,
  'spell:fly': 146,
  'spell:fog-cloud': 146,
  'spell:freezing-sphere': 147,
  'spell:geas': 148,
  'spell:globe-of-invulnerability': 149,
  'spell:glyph-of-warding': 149,
  'spell:guiding-bolt': 151,
  'spell:heal': 153,
  'spell:healing-word': 153,
  'spell:heat-metal': 153,
  'spell:hellish-rebuke': 154,
  'spell:heroism': 154,
  'spell:hold-monster': 154,
  'spell:hold-person': 154,
  'spell:hunters-mark': 155,
  'spell:ice-storm': 155,
  'spell:inflict-wounds': 157,
  'spell:insect-plague': 157,
  'spell:invisibility': 157,
  'spell:lightning-bolt': 159,
  'spell:longstrider': 160,
  'spell:magic-circle': 160,
  'spell:magic-missile': 161,
  'spell:magic-weapon': 161,
  'spell:major-image': 162,
  'spell:mass-cure-wounds': 162,
  'spell:mass-healing-word': 163,
  'spell:mass-suggestion': 163,
  'spell:modify-memory': 166,
  'spell:moonbeam': 166,
  'spell:phantasmal-killer': 167,
  'spell:planar-binding': 168,
  'spell:prayer-of-healing': 170,
  'spell:private-sanctum': 171,
  'spell:scorching-ray': 176,
  'spell:shatter': 178,
  'spell:sleep': 180,
  'spell:spirit-guardians': 182,
  'spell:spiritual-weapon': 182,
  'spell:thunderwave': 187,
  'spell:vampiric-touch': 189,
  'spell:wall-of-fire': 190,
  'spell:wall-of-ice': 190,
  'spell:wall-of-thorns': 191,
};
