import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { EQUIPMENT_MECHANICS_SPECS } from './importers/dnd5e-srd-5.1/equipmentMechanics.js';

const ROOT = resolve(import.meta.dirname, '../../..');
const RECORDS = resolve(
  ROOT,
  'packages/core/data/rules-packs/rules__dnd5e-srd-5.1/records.json',
);
const JSON_OUT = resolve(
  ROOT,
  'docs/audits/dnd5e-srd-5.1-final/o9bd-18-7-6-equipment-mechanics-inventory.json',
);
const MD_OUT = resolve(
  ROOT,
  'docs/audits/dnd5e-srd-5.1-final/o9bd-18-7-6-equipment-mechanics-inventory.md',
);

interface RecordRow {
  readonly kind: string;
  readonly key: string;
  readonly name: string;
  readonly source: string;
  readonly data: Record<string, unknown>;
}
const records = JSON.parse(readFileSync(RECORDS, 'utf8')) as RecordRow[];
const equipment = records.filter((record) => record.kind === 'equipment');
if (equipment.length !== 218)
  throw new Error(
    `equipment membership drift: expected 218, got ${equipment.length}`,
  );
const specs = new Map(
  EQUIPMENT_MECHANICS_SPECS.map((spec) => [spec.recordKey, spec]),
);
for (const key of specs.keys())
  if (!equipment.some((record) => record.key === key))
    throw new Error(`reviewed equipment record disappeared: ${key}`);

const structuredCategories = new Set([
  'armor',
  'weapon',
  'pack',
  'mount',
  'vehicle',
]);
const rows = equipment.map((record) => {
  const spec = specs.get(record.key);
  const hasDescription = typeof record.data.description === 'string';
  const alreadyComplete =
    structuredCategories.has(String(record.data.category)) ||
    record.data.capacity !== undefined;
  const disposition =
    spec !== undefined
      ? 'requires projection in this bead'
      : alreadyComplete
        ? 'already complete'
        : hasDescription
          ? 'model-adjudicated qualifier'
          : 'not mechanical';
  const tableDerivedFacts = Object.fromEntries(
    Object.entries(record.data).filter(
      ([key]) => !['description', 'useProfile'].includes(key),
    ),
  );
  return {
    recordKey: record.key,
    name: record.name,
    category: record.data.category,
    grouping: {
      equipmentGroup: record.data.equipmentGroup ?? null,
      weaponCategory: record.data.weaponCategory ?? null,
      weaponRange: record.data.weaponRange ?? null,
    },
    source: record.source,
    tableDerivedFacts,
    sourceDescriptionClauses: hasDescription ? [record.data.description] : [],
    mechanicallySignificantClauseIds:
      spec?.clauses.map((clause) => clause.id) ?? [],
    currentTypedRepresentation: Object.keys(tableDerivedFacts),
    requiredDeterministicRepresentation:
      spec !== undefined
        ? ['data.useProfile']
        : alreadyComplete
          ? ['table-derived fields']
          : [],
    disposition,
    engineToolOwners:
      spec === undefined
        ? []
        : [...new Set(spec.clauses.map((clause) => clause.owner))],
    sourceBindings:
      spec?.clauses.map((clause) => ({
        clauseId: clause.id,
        phrase: clause.sourcePhrase,
        pages: spec.pages,
      })) ?? [],
  };
});
const dispositionCounts = Object.fromEntries(
  [...new Set(rows.map((row) => row.disposition))]
    .sort()
    .map((disposition) => [
      disposition,
      rows.filter((row) => row.disposition === disposition).length,
    ]),
);
const artifact = {
  bead: 'eshyra-o9bd.18.7.6',
  generatedBy: 'packages/core/scripts/inventory-equipment-mechanics.ts',
  recordCount: rows.length,
  recordsWithDescriptions: rows.filter(
    (row) => row.sourceDescriptionClauses.length > 0,
  ).length,
  mechanicallyActiveRecords: rows.filter(
    (row) => row.disposition !== 'not mechanical',
  ).length,
  curatedProjectionRecords: specs.size,
  clauseCount: EQUIPMENT_MECHANICS_SPECS.reduce(
    (sum, spec) => sum + spec.clauses.length,
    0,
  ),
  dispositionCounts,
  records: rows,
};
const json = `${JSON.stringify(artifact, null, 2)}\n`;
const md = [
  '# SRD equipment mechanics inventory',
  '',
  `Generated by \`${artifact.generatedBy}\`. Do not hand-edit.`,
  '',
  `Records: **${artifact.recordCount}**; descriptions: **${artifact.recordsWithDescriptions}**; mechanically active: **${artifact.mechanicallyActiveRecords}**; curated projections: **${artifact.curatedProjectionRecords}**; clauses: **${artifact.clauseCount}**.`,
  '',
  '| record | category | source | disposition | clauses |',
  '| --- | --- | --- | --- | --- |',
  ...rows.map(
    (row) =>
      `| \`${row.recordKey}\` | ${row.category} | ${row.source} | ${row.disposition} | ${row.mechanicallySignificantClauseIds.join(', ') || '—'} |`,
  ),
  '',
].join('\n');
if (process.argv.includes('--check')) {
  if (
    JSON.stringify(JSON.parse(readFileSync(JSON_OUT, 'utf8'))) !==
      JSON.stringify(artifact) ||
    readFileSync(MD_OUT, 'utf8') !== md
  )
    throw new Error(
      'committed equipment mechanics inventory is stale; regenerate it',
    );
} else {
  writeFileSync(JSON_OUT, json);
  writeFileSync(MD_OUT, md);
}
