export type {
  AdditionalRequirement,
  CanonicalRequirement,
  CapabilityResolver,
  CompletenessEvaluationOptions,
  CompletenessReason,
  CompletenessResult,
  DimensionEvaluation,
  DimensionName,
  DiscoveryResolver,
  ReadinessEvaluation,
  RequirementPredicate,
  SemanticEvaluation,
  SourceEvidenceResolver,
} from './contracts.js';
export {
  BASE_REQUIREMENTS,
  evaluateClauseCompleteness,
  FACET_IMPLICATIONS,
  FACET_REQUIREMENTS,
  getFacetRequirements,
} from './contracts.js';
export type {
  FamilyApplicability,
  ObligationClosureEntry,
  ObligationClosureResult,
  ObligationMembership,
  ObligationRegistry,
  ObligationScope,
  ObligationScopeInput,
  UnexpectedObligationClaim,
} from './obligations.js';
export {
  createObligationId,
  createObligationRegistry,
  createObligationScope,
  evaluateObligationClosure,
  RECORD_FAMILY_APPLICABILITY,
} from './obligations.js';
export type {
  ActionEconomyCost,
  ActionEconomyKind,
  AlternativeSpec,
  AttackSpec,
  AuthoritativeInputEvidence,
  BranchSet,
  BranchSpec,
  CapabilityReference,
  CheckSpec,
  Clause,
  ClauseDimensions,
  ClauseField,
  ClauseIdentity,
  ClauseKind,
  ClausePredicate,
  ClauseProvenance,
  ClauseReadinessEvidence,
  DamageSpec,
  DiscoveryReference,
  DurationSpec,
  EngineCapability,
  ExecutionOwner,
  GeometrySpec,
  GrantSpec,
  HealingSpec,
  ImmunityWindowSpec,
  LedgerChangeSpec,
  MechanicsRecordFamily,
  ObligationEvidence,
  ObligationId,
  ObligationOrigin,
  RecordOwner,
  RecurrenceSpec,
  RegressionEvidence,
  RepeatCheckSpec,
  SaveSpec,
  SemanticFacet,
  SemanticOwner,
  SourceObligationRecord,
  SourceSpan,
  SourceSpanEvidence,
  StateTransitionSpec,
  TargetSpec,
  TerminationSpec,
} from './types.js';
